services:
  fastapi:
    image: abdocker0210/fastapi:latest
    networks:
      - learningassistant_app-network
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      PINECONE_ENVIRONMENT: ${PINECONE_ENVIRONMENT}
      INDEX_NAME: ${INDEX_NAME}
      IMG_INDEX_NAME: ${IMG_INDEX_NAME}
      DIMENSION: ${DIMENSION}
      METRIC: ${METRIC}
      FASTAPI_URL: ${FASTAPI_URL}
      SNOWFLAKE_USER: ${SNOWFLAKE_USER}
      SNOWFLAKE_PASSWORD: ${SNOWFLAKE_PASSWORD}
      SNOWFLAKE_ACCOUNT: ${SNOWFLAKE_ACCOUNT}
      SNOWFLAKE_WAREHOUSE: ${SNOWFLAKE_WAREHOUSE}
      SNOWFLAKE_DATABASE: ${SNOWFLAKE_DATABASE}
      SNOWFLAKE_SCHEMA: ${SNOWFLAKE_SCHEMA}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/docs || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  streamlit:
    image: abdocker0210/streamlit:latest
    networks:
      - learningassistant_app-network
    ports:
      - "8501:8501"
    depends_on:
      fastapi:
        condition: service_healthy
    environment:
      FASTAPI_URL: ${FASTAPI_URL}
      SECRET_KEY: ${SECRET_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      PINECONE_ENVIRONMENT: ${PINECONE_ENVIRONMENT}
      INDEX_NAME: ${INDEX_NAME}
      IMG_INDEX_NAME: ${IMG_INDEX_NAME}
      DIMENSION: ${DIMENSION}
      METRIC: ${METRIC}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8501 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  learningassistant_app-network:
    external: true
