services:
  fastapi:
    image: abdocker0210/fastapi:latest
    networks:
      - app-network
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${{ secrets.SECRET_KEY }}
      - OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
      - PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }}
      - PINECONE_ENVIRONMENT=${{ secrets.PINECONE_ENVIRONMENT }}
      - INDEX_NAME=${{ secrets.INDEX_NAME }}
      - IMG_INDEX_NAME=${{ secrets.IMG_INDEX_NAME }}
      - DIMENSION=${{ secrets.DIMENSION }}
      - METRIC=${{ secrets.METRIC }}
      - FASTAPI_URL=${{ secrets.FASTAPI_URL }}
      - SNOWFLAKE_USER=${{ secrets.SNOWFLAKE_USER }}
      - SNOWFLAKE_PASSWORD=${{ secrets.SNOWFLAKE_PASSWORD }}
      - SNOWFLAKE_ACCOUNT=${{ secrets.SNOWFLAKE_ACCOUNT }}
      - SNOWFLAKE_WAREHOUSE=${{ secrets.SNOWFLAKE_WAREHOUSE }}
      - SNOWFLAKE_DATABASE=${{ secrets.SNOWFLAKE_DATABASE }}
      - SNOWFLAKE_SCHEMA=${{ secrets.SNOWFLAKE_SCHEMA }}
    restart: always

  streamlit:
    image: abdocker0210/streamlit:latest
    networks:
      - app-network
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    environment:
      - FASTAPI_URL=${{ secrets.FASTAPI_URL }}
      - SECRET_KEY=${{ secrets.SECRET_KEY }}
      - OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
      - PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }}
      - PINECONE_ENVIRONMENT=${{ secrets.PINECONE_ENVIRONMENT }}
      - INDEX_NAME=${{ secrets.INDEX_NAME }}
      - IMG_INDEX_NAME=${{ secrets.IMG_INDEX_NAME }}
      - DIMENSION=${{ secrets.DIMENSION }}
      - METRIC=${{ secrets.METRIC }}
      - YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}
    restart: always

networks:
  app-network:
    driver: bridge
