services:
  fastapi:
    image: abdocker0210/fastapi:latest
    networks:
      - app-network
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      PINECONE_ENVIRONMENT: ${PINECONE_ENVIRONMENT}
      INDEX_NAME: ${INDEX_NAME}
      IMG_INDEX_NAME: ${IMG_INDEX_NAME}
      DIMENSION: ${DIMENSION}
      METRIC: ${METRIC}
      FASTAPI_URL: ${FASTAPI_URL}
      SNOWFLAKE_USER: ${SNOWFLAKE_USER}
      SNOWFLAKE_PASSWORD: ${SNOWFLAKE_PASSWORD}
      SNOWFLAKE_ACCOUNT: ${SNOWFLAKE_ACCOUNT}
      SNOWFLAKE_WAREHOUSE: ${SNOWFLAKE_WAREHOUSE}
      SNOWFLAKE_DATABASE: ${SNOWFLAKE_DATABASE}
      SNOWFLAKE_SCHEMA: ${SNOWFLAKE_SCHEMA}
    restart: always

  streamlit:
    image: abdocker0210/streamlit:latest
    networks:
      - app-network
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    environment:
      FASTAPI_URL: ${FASTAPI_URL}
      SECRET_KEY: ${SECRET_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      PINECONE_ENVIRONMENT: ${PINECONE_ENVIRONMENT}
      INDEX_NAME: ${INDEX_NAME}
      IMG_INDEX_NAME: ${IMG_INDEX_NAME}
      DIMENSION: ${DIMENSION}
      METRIC: ${METRIC}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
    restart: always

networks:
  app-network:
    driver: bridge
