name: Deploy AI Assistant

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Free up Disk Space
    - name: Free up disk space
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
        docker system prune -af || true
        df -h

    # Step 3: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 4: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 5: Cache Python Dependencies for FastAPI
    - name: Cache FastAPI Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-fastapi-${{ hashFiles('fastapi/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-pip-fastapi-

    # Build FastAPI Image
    - name: Build and push FastAPI image
      uses: docker/build-push-action@v4
      with:
        context: ./fastapi
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/fastapi:latest

    # Step 6: Cache Python Dependencies for Streamlit
    - name: Cache Streamlit Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-streamlit-${{ hashFiles('streamlit/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-pip-streamlit-

    # Build Streamlit Image
    - name: Build and push Streamlit image
      uses: docker/build-push-action@v4
      with:
        context: ./streamlit
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/streamlit:latest

    # Step 7: Debug Build Context
    - name: Debug build context for FastAPI
      run: ls -R ./fastapi

    - name: Debug build context for Streamlit
      run: ls -R ./streamlit

    # Step 8: Deploy to EC2 via SSH
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          set -e
          cd /home/ubuntu/LearningAssistant
          echo "Updating images..."
          sudo docker-compose pull
          echo "Starting services with environment variables..."
          sudo docker-compose up -d --remove-orphans

    # Step 9: Verify Deployment
    - name: Check services health
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          set -e
          echo "Checking FastAPI service health..."
          for i in {1..5}; do
            curl -f http://localhost:8000/docs && break || echo "Retrying FastAPI health check..." && sleep 5
          done
          echo "Checking Streamlit service health..."
          for i in {1..5}; do
            curl -f http://localhost:8501 && break || echo "Retrying Streamlit health check..." && sleep 5
          done
