name: Deploy AI Assistant

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Updated to use the self-hosted runner

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Free up Disk Space
    - name: Free up disk space
      run: |
        echo "Cleaning up unused resources..."
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
        docker system prune -af || true
        docker volume prune -f || true
        df -h

    # Step 3: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 4: Log in to DockerHub
    - name: Log in to DockerHub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Step 5: Build FastAPI Image
    - name: Build and push FastAPI image
      run: |
        docker buildx build \
          --platform linux/amd64 \
          --push \
          --cache-from=type=registry,ref=${{ secrets.DOCKER_USERNAME }}/fastapi:latest \
          --cache-to=type=inline \
          --tag ${{ secrets.DOCKER_USERNAME }}/fastapi:latest \
          --tag ${{ secrets.DOCKER_USERNAME }}/fastapi:${{ github.sha }} \
          ./fastapi

    # Step 6: Build Streamlit Image
    - name: Build and push Streamlit image
      run: |
        docker buildx build \
          --platform linux/amd64 \
          --push \
          --cache-from=type=registry,ref=${{ secrets.DOCKER_USERNAME }}/streamlit:latest \
          --cache-to=type=inline \
          --tag ${{ secrets.DOCKER_USERNAME }}/streamlit:latest \
          --tag ${{ secrets.DOCKER_USERNAME }}/streamlit:${{ github.sha }} \
          ./streamlit

    # Step 7: Debug Build Context
    - name: Debug build context for FastAPI
      run: ls -R ./fastapi

    - name: Debug build context for Streamlit
      run: ls -R ./streamlit

    # Step 8: Create .env file for secrets
    - name: Create .env file
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
        echo "PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }}" >> .env
        echo "INDEX_NAME=${{ secrets.INDEX_NAME }}" >> .env
        echo "IMG_INDEX_NAME=${{ secrets.IMG_INDEX_NAME }}" >> .env
        echo "DIMENSION=${{ secrets.DIMENSION }}" >> .env
        echo "METRIC=${{ secrets.METRIC }}" >> .env
        echo "FASTAPI_URL=${{ secrets.FASTAPI_URL }}" >> .env
        echo "SNOWFLAKE_USER=${{ secrets.SNOWFLAKE_USER }}" >> .env
        echo "SNOWFLAKE_PASSWORD=${{ secrets.SNOWFLAKE_PASSWORD }}" >> .env
        echo "SNOWFLAKE_ACCOUNT=${{ secrets.SNOWFLAKE_ACCOUNT }}" >> .env
        echo "SNOWFLAKE_WAREHOUSE=${{ secrets.SNOWFLAKE_WAREHOUSE }}" >> .env
        echo "SNOWFLAKE_DATABASE=${{ secrets.SNOWFLAKE_DATABASE }}" >> .env
        echo "SNOWFLAKE_SCHEMA=${{ secrets.SNOWFLAKE_SCHEMA }}" >> .env
        echo "YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}" >> .env
        echo "CLOUD_PROVIDER=${{ secrets.CLOUD_PROVIDER }}" >> .env 
        echo "REGION=${{ secrets.REGION }}" >> .env                  


    # Step 9: Ensure Docker Network Exists
    - name: Ensure Docker Network Exists
      run: |
        docker network inspect learningassistant_app-network || docker network create learningassistant_app-network

    # Step 10: Deploy with Docker Compose
    - name: Deploy with Docker Compose
      run: |
        docker-compose pull
        docker-compose up -d --remove-orphans

    # Step 11: Verify Deployment
    - name: Check FastAPI service health
      run: |
        retries=10
        delay=10
        for i in $(seq 1 $retries); do
          echo "Checking FastAPI service health (attempt $i/$retries)..."
          curl -f http://localhost:8000/docs && break || sleep $delay
        done

    - name: Check Streamlit service health
      run: |
        retries=10
        delay=10
        for i in $(seq 1 $retries); do
          echo "Checking Streamlit service health (attempt $i/$retries)..."
          curl -f http://localhost:8501 && break || sleep $delay
        done
